package GUI;

import Entidade.ManutencaoException;
import Entidade.QuilometragemException;
import Classes.Utils;
import Entidade.Veiculo;
import Entidade.VeiculoException;
import Fachada.FacDashboard;
import Fachada.FacVeiculo;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GOMES
 */
public class JPDashboard extends javax.swing.JPanel {

    /**
     * Creates new form JPDashboard
     */
    private final Veiculo veiculo;
    private final Fachada.FacVeiculo facvei;
    private final Fachada.FacDashboard facdash;
  
    
    DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
    DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
    DefaultTableCellRenderer direita = new DefaultTableCellRenderer();




    public JPDashboard() {
        initComponents();
        //this.JTextPlaca.requestFocus();
        //this.JPDashboardMain.setVisible(false);
        this.JPDashboardTop.setVisible(false);
        this.JPMainContent.setVisible(false);

        this.veiculo = new Veiculo();
        this.facvei = new FacVeiculo();
        this.facdash = new FacDashboard();

        this.JLCarregando.setVisible(false);
        
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        this.CarregaComboPlaca();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLHome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLCarregando = new javax.swing.JLabel();
        JPDashboardMain = new javax.swing.JPanel();
        JPDashboardTop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpMediaKMDia = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        JLMediaKMDia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jpMediaKMMes = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        JLMediaKMMes = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jpTotalKM = new javax.swing.JLabel();
        JLTotalKMRodado = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        JLValorTotal = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        JLQtdMeses = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        JLProprietario = new javax.swing.JLabel();
        JLKMCompra = new javax.swing.JLabel();
        JLKMAtual = new javax.swing.JLabel();
        JLDataCompra = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        JLDataKmAtual = new javax.swing.JLabel();
        JPMainContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTManutencaoTodas = new GUI.jTableCustom();
        JLProximasManutencao = new javax.swing.JLabel();
        JLTodasManutencao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTManutencaoProximas = new GUI.jTableCustom();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTManutencaoVencidas = new GUI.jTableCustom();
        JLVencidasManutencao = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JBCarregaDashbord = new javax.swing.JButton();
        jComboBoxPlaca = new GUI.JComboBoxCustom();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        JLHome.setBackground(new java.awt.Color(255, 255, 255));
        JLHome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        JLHome.setForeground(new java.awt.Color(0, 102, 153));
        JLHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-casa-14.png"))); // NOI18N
        JLHome.setText("Home");
        JLHome.setToolTipText("");
        JLHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JLHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLHomeMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(">");
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Dashboard");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLCarregando.setBackground(new java.awt.Color(255, 255, 255));
        JLCarregando.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        JLCarregando.setForeground(new java.awt.Color(0, 102, 153));
        JLCarregando.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLCarregando.setText("Carregando, aguarde...");
        JLCarregando.setToolTipText("");
        JLCarregando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JPDashboardMain.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        JPDashboardTop.setAutoscrolls(true);
        JPDashboardTop.setName("JPDashboarTop"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jpMediaKMDia.setBackground(new java.awt.Color(0, 102, 153));
        jpMediaKMDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Média KM dia");
        jLabel22.setToolTipText("");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpMediaKMDiaLayout = new javax.swing.GroupLayout(jpMediaKMDia);
        jpMediaKMDia.setLayout(jpMediaKMDiaLayout);
        jpMediaKMDiaLayout.setHorizontalGroup(
            jpMediaKMDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMediaKMDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMediaKMDiaLayout.setVerticalGroup(
            jpMediaKMDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMediaKMDiaLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JLMediaKMDia.setBackground(new java.awt.Color(255, 255, 255));
        JLMediaKMDia.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JLMediaKMDia.setForeground(new java.awt.Color(0, 102, 153));
        JLMediaKMDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMediaKMDia.setText("0,00");
        JLMediaKMDia.setToolTipText("");
        JLMediaKMDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMediaKMDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLMediaKMDia, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpMediaKMDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(JLMediaKMDia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jpMediaKMMes.setBackground(new java.awt.Color(0, 102, 153));
        jpMediaKMMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Média KM mês");
        jLabel25.setToolTipText("");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpMediaKMMesLayout = new javax.swing.GroupLayout(jpMediaKMMes);
        jpMediaKMMes.setLayout(jpMediaKMMesLayout);
        jpMediaKMMesLayout.setHorizontalGroup(
            jpMediaKMMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMediaKMMesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpMediaKMMesLayout.setVerticalGroup(
            jpMediaKMMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMediaKMMesLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JLMediaKMMes.setBackground(new java.awt.Color(255, 255, 255));
        JLMediaKMMes.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JLMediaKMMes.setForeground(new java.awt.Color(0, 102, 153));
        JLMediaKMMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLMediaKMMes.setText("0,00");
        JLMediaKMMes.setToolTipText("");
        JLMediaKMMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMediaKMMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLMediaKMMes, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpMediaKMMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(JLMediaKMMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpTotalKM.setBackground(new java.awt.Color(255, 255, 255));
        jpTotalKM.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jpTotalKM.setForeground(new java.awt.Color(255, 255, 255));
        jpTotalKM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpTotalKM.setText("Total KM");
        jpTotalKM.setToolTipText("");
        jpTotalKM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTotalKM, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jpTotalKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JLTotalKMRodado.setBackground(new java.awt.Color(255, 255, 255));
        JLTotalKMRodado.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JLTotalKMRodado.setForeground(new java.awt.Color(0, 102, 153));
        JLTotalKMRodado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTotalKMRodado.setText("0");
        JLTotalKMRodado.setToolTipText("");
        JLTotalKMRodado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLTotalKMRodado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(JLTotalKMRodado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Total $");
        jLabel29.setToolTipText("");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JLValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        JLValorTotal.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JLValorTotal.setForeground(new java.awt.Color(0, 102, 153));
        JLValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLValorTotal.setText("0,00");
        JLValorTotal.setToolTipText("");
        JLValorTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(JLValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jPanel10.setBackground(new java.awt.Color(0, 102, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Qtd. Meses");
        jLabel31.setToolTipText("");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JLQtdMeses.setBackground(new java.awt.Color(255, 255, 255));
        JLQtdMeses.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        JLQtdMeses.setForeground(new java.awt.Color(0, 102, 153));
        JLQtdMeses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLQtdMeses.setText("0");
        JLQtdMeses.setToolTipText("");
        JLQtdMeses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JLQtdMeses, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(JLQtdMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));

        jPanel12.setBackground(new java.awt.Color(0, 102, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Informações gerais");
        jLabel33.setToolTipText("");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 153));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Proprietário:");
        jLabel34.setToolTipText("");
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 153));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("KM Compra:");
        jLabel35.setToolTipText("");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 153));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Data inicial:");
        jLabel36.setToolTipText("");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 102, 153));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("KM Atual:");
        jLabel37.setToolTipText("");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLProprietario.setBackground(new java.awt.Color(255, 255, 255));
        JLProprietario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLProprietario.setForeground(new java.awt.Color(0, 102, 153));
        JLProprietario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLProprietario.setToolTipText("");
        JLProprietario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLKMCompra.setBackground(new java.awt.Color(255, 255, 255));
        JLKMCompra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLKMCompra.setForeground(new java.awt.Color(0, 102, 153));
        JLKMCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLKMCompra.setToolTipText("");
        JLKMCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLKMAtual.setBackground(new java.awt.Color(255, 255, 255));
        JLKMAtual.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLKMAtual.setForeground(new java.awt.Color(0, 102, 153));
        JLKMAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLKMAtual.setToolTipText("");
        JLKMAtual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLDataCompra.setBackground(new java.awt.Color(255, 255, 255));
        JLDataCompra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLDataCompra.setForeground(new java.awt.Color(0, 102, 153));
        JLDataCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLDataCompra.setToolTipText("");
        JLDataCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 153));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Dt. Atual");
        jLabel41.setToolTipText("");
        jLabel41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLDataKmAtual.setBackground(new java.awt.Color(255, 255, 255));
        JLDataKmAtual.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLDataKmAtual.setForeground(new java.awt.Color(0, 102, 153));
        JLDataKmAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLDataKmAtual.setToolTipText("");
        JLDataKmAtual.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLKMCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLDataCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLKMAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLDataKmAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(JLProprietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(JLKMCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(JLDataCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(JLKMAtual)
                    .addComponent(jLabel41)
                    .addComponent(JLDataKmAtual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPDashboardTopLayout = new javax.swing.GroupLayout(JPDashboardTop);
        JPDashboardTop.setLayout(JPDashboardTopLayout);
        JPDashboardTopLayout.setHorizontalGroup(
            JPDashboardTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPDashboardTopLayout.setVerticalGroup(
            JPDashboardTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPDashboardTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JPMainContent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manutenções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N

        JTManutencaoTodas.setAutoCreateRowSorter(true);
        JTManutencaoTodas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID-TIPO MANUTENÇÃO", "DT. REALIZAÇÃO", "KM. MANUTENÇÃO", "VALOR", "SITUAÇÃO", "OBSERVAÇÃO", "KM. SUBSTITUIÇÃO", "DT. SUBSTITUIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTManutencaoTodas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTManutencaoTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTManutencaoTodasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTManutencaoTodas);
        if (JTManutencaoTodas.getColumnModel().getColumnCount() > 0) {
            JTManutencaoTodas.getColumnModel().getColumn(0).setPreferredWidth(200);
            JTManutencaoTodas.getColumnModel().getColumn(1).setPreferredWidth(120);
            JTManutencaoTodas.getColumnModel().getColumn(2).setPreferredWidth(120);
            JTManutencaoTodas.getColumnModel().getColumn(3).setPreferredWidth(100);
            JTManutencaoTodas.getColumnModel().getColumn(4).setPreferredWidth(120);
            JTManutencaoTodas.getColumnModel().getColumn(5).setPreferredWidth(250);
            JTManutencaoTodas.getColumnModel().getColumn(6).setPreferredWidth(120);
            JTManutencaoTodas.getColumnModel().getColumn(7).setPreferredWidth(120);
        }

        JLProximasManutencao.setBackground(new java.awt.Color(255, 255, 255));
        JLProximasManutencao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        JLProximasManutencao.setForeground(new java.awt.Color(0, 153, 51));
        JLProximasManutencao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLProximasManutencao.setText("Válido");
        JLProximasManutencao.setToolTipText("");
        JLProximasManutencao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JLTodasManutencao.setBackground(new java.awt.Color(255, 255, 255));
        JLTodasManutencao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        JLTodasManutencao.setForeground(new java.awt.Color(0, 102, 153));
        JLTodasManutencao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLTodasManutencao.setText("Todas");
        JLTodasManutencao.setToolTipText("");
        JLTodasManutencao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JTManutencaoProximas.setAutoCreateRowSorter(true);
        JTManutencaoProximas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID-TIPO MANUTENÇÃO", "DATA VENC.", "QUILOMETRAGEM VENC.", "PREV. MÊS/ANO", "KM UTILIZADO", "KM RESTANTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTManutencaoProximas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(JTManutencaoProximas);
        if (JTManutencaoProximas.getColumnModel().getColumnCount() > 0) {
            JTManutencaoProximas.getColumnModel().getColumn(0).setPreferredWidth(200);
            JTManutencaoProximas.getColumnModel().getColumn(1).setPreferredWidth(120);
            JTManutencaoProximas.getColumnModel().getColumn(2).setPreferredWidth(150);
            JTManutencaoProximas.getColumnModel().getColumn(3).setPreferredWidth(120);
            JTManutencaoProximas.getColumnModel().getColumn(4).setPreferredWidth(120);
            JTManutencaoProximas.getColumnModel().getColumn(5).setPreferredWidth(120);
        }

        JTManutencaoVencidas.setAutoCreateRowSorter(true);
        JTManutencaoVencidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID-TIPO MANUTENÇÃO", "DT. VENCIMENTO", "KM. VENCIMENTO", "KM. EXCEDENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTManutencaoVencidas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(JTManutencaoVencidas);
        if (JTManutencaoVencidas.getColumnModel().getColumnCount() > 0) {
            JTManutencaoVencidas.getColumnModel().getColumn(0).setPreferredWidth(250);
            JTManutencaoVencidas.getColumnModel().getColumn(1).setPreferredWidth(120);
            JTManutencaoVencidas.getColumnModel().getColumn(2).setPreferredWidth(120);
            JTManutencaoVencidas.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        JLVencidasManutencao.setBackground(new java.awt.Color(255, 255, 255));
        JLVencidasManutencao.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        JLVencidasManutencao.setForeground(new java.awt.Color(255, 0, 0));
        JLVencidasManutencao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLVencidasManutencao.setText("Vencidas");
        JLVencidasManutencao.setToolTipText("");
        JLVencidasManutencao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout JPMainContentLayout = new javax.swing.GroupLayout(JPMainContent);
        JPMainContent.setLayout(JPMainContentLayout);
        JPMainContentLayout.setHorizontalGroup(
            JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMainContentLayout.createSequentialGroup()
                .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPMainContentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JLTodasManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPMainContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPMainContentLayout.createSequentialGroup()
                        .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLProximasManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLVencidasManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPMainContentLayout.createSequentialGroup()
                        .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
        );
        JPMainContentLayout.setVerticalGroup(
            JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPMainContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLProximasManutencao)
                    .addComponent(JLTodasManutencao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(JPMainContentLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLVencidasManutencao)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPDashboardMainLayout = new javax.swing.GroupLayout(JPDashboardMain);
        JPDashboardMain.setLayout(JPDashboardMainLayout);
        JPDashboardMainLayout.setHorizontalGroup(
            JPDashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPDashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPDashboardMainLayout.createSequentialGroup()
                        .addComponent(JPMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(JPDashboardTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        JPDashboardMainLayout.setVerticalGroup(
            JPDashboardMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPDashboardTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 153));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Placa");
        jLabel26.setToolTipText("");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JBCarregaDashbord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JBCarregaDashbord.setForeground(new java.awt.Color(0, 102, 153));
        JBCarregaDashbord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-a-carregar-24 (1).png"))); // NOI18N
        JBCarregaDashbord.setToolTipText("Carregar informações.");
        JBCarregaDashbord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JBCarregaDashbord.setBorderPainted(false);
        JBCarregaDashbord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBCarregaDashbord.setFocusPainted(false);
        JBCarregaDashbord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBCarregaDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBCarregaDashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBCarregaDashbordMouseExited(evt);
            }
        });
        JBCarregaDashbord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCarregaDashbordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jComboBoxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBCarregaDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(JPDashboardMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLCarregando)
                        .addComponent(jComboBoxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLHome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBCarregaDashbord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPDashboardMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JLHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLHomeMouseClicked
        JFPrincipal.setPanelMain(new JPHome());
    }//GEN-LAST:event_JLHomeMouseClicked

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.updateUI();
    }//GEN-LAST:event_formComponentResized

    private void JBCarregaDashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCarregaDashbordMouseEntered
         this.JBCarregaDashbord.setBackground(new Color(169,169,169));
    }//GEN-LAST:event_JBCarregaDashbordMouseEntered

    private void JBCarregaDashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCarregaDashbordMouseExited
        this.JBCarregaDashbord.setBackground(this.getBackground());
    }//GEN-LAST:event_JBCarregaDashbordMouseExited

    private void JBCarregaDashbordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCarregaDashbordActionPerformed
        this.carregaDashBoard();
    }//GEN-LAST:event_JBCarregaDashbordActionPerformed

    
 
      private void CarregaComboPlaca() {

        try {

            Veiculo v = new Veiculo();
            v.setID(-1);
            v.setPlaca("");

            List<Veiculo> listv = new ArrayList<>();
            listv = this.facvei.Consultar(v);

            Collections.sort(listv, Comparator.comparing(Veiculo::getModelo));

            this.jComboBoxPlaca.addItem("-- Selecione --");
       
            this.jComboBoxPlaca.setSelectedIndex(0);
       
            int[] listaInt = new int[listv.size() + 1];

            for (int x = 1; x <= listv.size(); x++) {
                listaInt[x] = listv.get(x - 1).getID();
                this.jComboBoxPlaca.addItem(listv.get(x - 1).getPlaca());
                        }

            this.jComboBoxPlaca.setCodCombo(listaInt);
     

        } catch (QuilometragemException | ManutencaoException | VeiculoException qe) {
            JOptionPane.showMessageDialog(null, qe.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void carregaDashBoard(){
    
        try {

            if (this.jComboBoxPlaca.getSelectedIndex() == 0) {

                throw new VeiculoException("Selecione a placa do veículo.");
            }

            this.JPDashboardTop.setVisible(false);
            this.JPMainContent.setVisible(false);

            Thread tr1 = new Thread() {
                @Override
                public void run() {
                    JLCarregando.setVisible(true);
                }
            };

            Thread tr2 = new Thread() {
                @Override
                public void run() {

                    try {
                        CarregaDasboard();
                        JPDashboardTop.setVisible(true);
                        JPMainContent.setVisible(true);
                        JLCarregando.setVisible(false);
                    } catch (VeiculoException qe) {
                        JLCarregando.setVisible(false);
                        JOptionPane.showMessageDialog(null, qe.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
                    } catch (Exception ex) {
                        JLCarregando.setVisible(false);
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }

            };

            tr1.start();
            tr2.start();

        } catch (VeiculoException qe) {
            JOptionPane.showMessageDialog(null, qe.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    
    }
    
    
    private void JTManutencaoTodasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTManutencaoTodasMouseClicked
    
    }//GEN-LAST:event_JTManutencaoTodasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCarregaDashbord;
    private javax.swing.JLabel JLCarregando;
    private javax.swing.JLabel JLDataCompra;
    private javax.swing.JLabel JLDataKmAtual;
    private javax.swing.JLabel JLHome;
    private javax.swing.JLabel JLKMAtual;
    private javax.swing.JLabel JLKMCompra;
    private javax.swing.JLabel JLMediaKMDia;
    private javax.swing.JLabel JLMediaKMMes;
    private javax.swing.JLabel JLProprietario;
    private javax.swing.JLabel JLProximasManutencao;
    private javax.swing.JLabel JLQtdMeses;
    private javax.swing.JLabel JLTodasManutencao;
    private javax.swing.JLabel JLTotalKMRodado;
    private javax.swing.JLabel JLValorTotal;
    private javax.swing.JLabel JLVencidasManutencao;
    private javax.swing.JPanel JPDashboardMain;
    private javax.swing.JPanel JPDashboardTop;
    private javax.swing.JPanel JPMainContent;
    private GUI.jTableCustom JTManutencaoProximas;
    private GUI.jTableCustom JTManutencaoTodas;
    private GUI.jTableCustom JTManutencaoVencidas;
    private GUI.JComboBoxCustom jComboBoxPlaca;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpMediaKMDia;
    private javax.swing.JPanel jpMediaKMMes;
    private javax.swing.JLabel jpTotalKM;
    // End of variables declaration//GEN-END:variables

    private void CarregaVeiculo(String placa) throws Exception, VeiculoException {

        Veiculo vi = new Veiculo();
        vi.setPlaca(placa);

        List<Veiculo> listv = new ArrayList<>();

        listv = this.facvei.Consultar(vi);

        if (listv.size() > 0) {

            this.veiculo.setID(listv.get(0).getID());
            this.veiculo.setAnoFabricacao(listv.get(0).getAnoFabricacao());
            this.veiculo.setProprietario(listv.get(0).getProprietario());
            this.veiculo.setKmInicial(listv.get(0).getKmInicial());
            this.veiculo.setDataCompra(listv.get(0).getDataCompra());
            this.veiculo.setPlaca(listv.get(0).getPlaca());

        } else {
            throw new VeiculoException("Veículo não encontrado no cadastro do sistema.");
        }

    }

    private void CarregaDadosGerais(Veiculo v) throws Exception {

        List<Object> listobj = new ArrayList<>();

        listobj = this.facdash.CarregaDadosGerais(v);

        if (listobj.size() > 0) {

            this.JLProprietario.setText((String) ((Object[]) listobj.get(0))[0]);
            this.JLKMCompra.setText((String) ((Object[]) listobj.get(0))[2]);
            this.JLDataCompra.setText((String) ((Object[]) listobj.get(0))[1]);
            this.JLKMAtual.setText((String) ((Object[]) listobj.get(0))[3]);
            this.JLValorTotal.setText((String) ((Object[]) listobj.get(0))[4]);
            this.JLDataKmAtual.setText((String) ((Object[]) listobj.get(0))[5]);

            String kminicial = (String) ((Object[]) listobj.get(0))[3];
            String kmatual = (String) ((Object[]) listobj.get(0))[2];

            kminicial = kminicial.replace(".", "");
            kmatual = kmatual.replace(".", "");

           
            int kmrodado = Integer.parseInt(kminicial) - Integer.parseInt(kmatual);
            this.JLTotalKMRodado.setText(Utils.FormartDecimal("###,###", kmrodado));

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate d1 = LocalDate.parse(this.JLDataCompra.getText().replace("-", "/"), formatter);
            LocalDate d2 = LocalDate.parse(this.JLDataKmAtual.getText().replace("-", "/"), formatter);
            LocalDate dataini = LocalDate.of(d1.getYear(), d1.getMonthValue(), d1.getDayOfMonth());
            LocalDate datafim = LocalDate.of(d2.getYear(), d2.getMonthValue(), d2.getDayOfMonth());
            long diferencaEmDias = ChronoUnit.DAYS.between(dataini, datafim);
            long diferencaEmMes = ChronoUnit.MONTHS.between(dataini, datafim);
            this.JLQtdMeses.setText(Long.toString(diferencaEmMes));

            if (kmrodado > 0) {

                double mediakmmes = Double.parseDouble(this.JLTotalKMRodado.getText().replace(".", "")) / Double.parseDouble(this.JLQtdMeses.getText());
                
                if (Integer.parseInt(this.JLQtdMeses.getText())>0) {
                   this.JLMediaKMMes.setText(Utils.FormartDecimal("###,###", mediakmmes)); 
                }               

                double totalkm = Long.parseLong(this.JLTotalKMRodado.getText().replace(".", ""));

                if (totalkm > 0 && diferencaEmDias >0) {
                    double mediakmdia = totalkm / diferencaEmDias;
                    this.JLMediaKMDia.setText(Utils.FormartDecimal("##.##", mediakmdia));
                }
                
  

            } else {
                this.JLMediaKMDia.setText("0");
                this.JLMediaKMMes.setText("0");

            }

        } else {

            this.JLProprietario.setText("");
            this.JLKMCompra.setText("");
            this.JLDataCompra.setText("");
            this.JLKMAtual.setText("");

            this.JLTotalKMRodado.setText("");
            this.JLValorTotal.setText("");
            this.JLDataKmAtual.setText("");
            this.JLMediaKMMes.setText("");

        }

    }

    private void CarregaDasboard() throws Exception, VeiculoException {

        Thread.sleep(3000);

        this.CarregaVeiculo(this.jComboBoxPlaca.getSelectedItem().toString().trim());
        this.CarregaDadosGerais(this.veiculo);
        this.CarregaTabelaTodasManutencao(this.veiculo);
        this.CarregaTabelaProximasManutencao(this.veiculo);
        this.CarregaTabelaVencidasManutencao(this.veiculo);

    }

    private void CarregaTabelaTodasManutencao(Veiculo veiculo) throws Exception {
       
        this.JTManutencaoTodas.deleteRows();
              
        DefaultTableModel dtm = (DefaultTableModel) this.JTManutencaoTodas.getModel();
        
        List<Object> list = new ArrayList<>();
        list = this.facdash.CarregaTabelaTodasManutencao(veiculo);
        
        for (Object object : list) {
            
            dtm.addRow((Object[]) object);
            
        }
        
        int qtdrows = this.JTManutencaoTodas.getRowCount();      
        this.JLTodasManutencao.setText("Todas" + " ("+ qtdrows+")");
        
        this.JTManutencaoTodas.ColorRow(JTManutencaoTodas, new String[]{"E","C","D","D","E","E","D","C"});
        
        
    }
    
    private void CarregaTabelaProximasManutencao(Veiculo veiculo) throws Exception {
       
        this.JTManutencaoProximas.deleteRows();

        DefaultTableModel dtm = (DefaultTableModel) this.JTManutencaoProximas.getModel();
        
        List<Object> list = new ArrayList<>();
        list = this.facdash.CarregaTabelaProximasManutencao(veiculo);
        
        
            if (list.size()>0) {
 
                for (int i = 0; i < list.size(); i++) {
                    
                    
                    String kmutilizado = ((String) ((Object[]) list.get(i))[4]);
                       int kmtipoman = ((int) ((Object[]) list.get(i))[5]);
                    
                    int kmuti =   Integer.parseInt(this.JLKMAtual.getText().replace(".", "")) - Integer.parseInt(kmutilizado.replace(".", ""));
                    int kmrestante = kmtipoman - kmuti;
                    
                    double dtprevista = Double.parseDouble(this.JLMediaKMDia.getText().replace(",","."));
                    
                    dtprevista =Math.round(dtprevista);
                    
                    dtprevista =  kmrestante / dtprevista;
                    
                    Date dataquilo = Utils.ConvertStringToDate("dd/MM/yyyy", this.JLDataKmAtual.getText());
                    
                     Calendar c = Calendar.getInstance();
                     c.setTime(dataquilo);
                     c.add(Calendar.DATE, (int) dtprevista);

   
                    Object[] row = {(String) ((Object[]) list.get(i))[0],
                                    (String) ((Object[]) list.get(i))[1],
                                    (String) ((Object[]) list.get(i))[2],
                                     Utils.FormatData("MMM/yyyy", c.getTime()).toUpperCase() ,
                                     Utils.FormartDecimal("###,###", kmuti),
                                     Utils.FormartDecimal("###,###", kmrestante)};                  
                    dtm.addRow(row); 
                }

            }
            
        int qtdrows = this.JTManutencaoProximas.getRowCount();      
        this.JLProximasManutencao.setText("Válido" + " ("+ qtdrows+")");
        
        
        this.JTManutencaoProximas.ColorRow(JTManutencaoProximas, new String[]{"E","C","D","C","D","D"});

    }

    private void CarregaTabelaVencidasManutencao(Veiculo veiculo) throws Exception {
       this.JTManutencaoVencidas.deleteRows();
    
        DefaultTableModel dtm = (DefaultTableModel) this.JTManutencaoVencidas.getModel();
        
        List<Object> list = new ArrayList<>();
        list = this.facdash.CarregaTabelaVencidasManutencao(veiculo);
               
            if (list.size()>0) {
 
                for (int i = 0; i < list.size(); i++) {
           
                    String kmexcedestr = (String) ((Object[]) list.get(i))[2];
                    int kmexcede =  Integer.parseInt(this.JLKMAtual.getText().replace(".","")) - Integer.parseInt(kmexcedestr.replace(".", ""));

                    Object[] row = {(String) ((Object[]) list.get(i))[0],
                                    (String) ((Object[]) list.get(i))[1],
                                    (String) ((Object[]) list.get(i))[2],
                                    Utils.FormartDecimal("###,###", kmexcede)};                  
                    dtm.addRow(row); 
                }

            }
        int qtdrows = this.JTManutencaoVencidas.getRowCount();      
        this.JLVencidasManutencao.setText("Vencida" + " ("+ qtdrows+")");
        
         this.JTManutencaoVencidas.ColorRow(JTManutencaoVencidas, new String[]{"E","C","D","D"});
        
    }

}
